[package]
name = "libsqlite3-extensions"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsqlite3-sys = "0.24.2"

[build-dependencies]
cc = "1.0.79"
