name: Publish

on:
  push:
    tags:
      - '*'

env:
  APPNAME: indexref-server

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: $APPNAME
            asset_name: $APPNAME-linux.zip
          - os: windows-latest
            binary: $APPNAME.exe
            asset_name: $APPNAME-windows.zip
          - os: macos-latest
            binary: $APPNAME
            asset_name: $APPNAME-macos.zip

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build Server
      run: cargo build --release --features static_server --locked

    - uses: actions/setup-node@v3
    - name: Build Client
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Archive
      run: |
        mkdir ./target/$APPNAME
        cp ./target/release/${{ matrix.binary }} ./target/$APPNAME/${{ matrix.binary }}
        cp -r ./client/dist/ ./target/$APPNAME/static
        (cd ./target; zip -r -D $APPNAME.zip ./$APPNAME || 7z a -tzip $APPNAME.zip ./$APPNAME)
      shell: bash

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ env.APPNAME }}.zip
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
